---

# Provision Ansible controller with SSH key for remote
- hosts: localhost
  roles:
    - ssh-key
  vars:
    ssh_key_name: ansible_remote
    hashicorp_vault_private_key_path: "applications/heritage-{{ environment_name }}-eu-west-2/chips-oltp/db/ec2"

# Configure target hosts
- hosts: tag_Application_CHIPS_OLTP
  become: true
  remote_user: ec2-user
  roles:
    - { role: oracle-logs, tags: oracle-logs }
    - { role: dbaops-scripts, tags: dbaops-scripts }
