---

- name: Copy CloudWatch Agent configuration
  template:
    src: ".{{ oracle_logs_cwagent_config_file }}.j2"
    dest: "{{ oracle_logs_cwagent_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart cloudwatch agent
